// Helpers for the Archidekt viewer: parsing raw deck JSON (as exported by the
// local deck-collector app's "Raw JSON" export) and rendering exports.
// Mirrors deck-collector/lib — kept dependency-free so it runs in the browser.

import type { ArchDeck, ArchCard } from '../db/archidektViewer';

// Observed Archidekt numeric format codes (same table as deck-collector).
export const ARCH_FORMAT_NAMES: Record<number, string> = {
  1: 'Standard',
  2: 'Modern',
  3: 'Commander / EDH',
  4: 'Legacy',
  5: 'Vintage',
  6: 'Pauper',
  7: 'Custom',
  9: 'Future Standard',
  10: 'Penny Dreadful',
  11: '1v1 Commander',
  12: 'Duel Commander',
  13: 'Brawl',
  14: 'Oathbreaker',
  15: 'Pioneer',
  16: 'Historic',
  17: 'Pauper EDH',
};

export function archFormatName(code: number | null | undefined): string {
  if (code === null || code === undefined) return '—';
  return ARCH_FORMAT_NAMES[code] ?? `Format #${code}`;
}

// Raw API shapes (loose — we defend with optional chaining everywhere).
interface RawCardEntry {
  quantity?: number;
  categories?: string[] | null;
  card?: {
    uid?: string;
    collectorNumber?: string | number;
    displayName?: string | null;
    edition?: { editioncode?: string } | null;
    oracleCard?: { name?: string } | null;
  } | null;
}

export interface RawDeck {
  id: number;
  name?: string;
  deckFormat?: number | null;
  owner?: { username?: string } | null;
  createdAt?: string;
  updatedAt?: string;
  cards?: RawCardEntry[];
}

function extractCardName(entry: RawCardEntry): string {
  return (
    entry.card?.oracleCard?.name ??
    entry.card?.displayName ??
    '(unknown card)'
  );
}

/** Convert one raw Archidekt deck into viewer rows. */
export function parseRawDeck(raw: RawDeck): { deck: ArchDeck; cards: ArchCard[] } {
  const cards: ArchCard[] = (raw.cards ?? []).map(entry => ({
    deckId: raw.id,
    cardName: extractCardName(entry),
    quantity: entry.quantity ?? 1,
    category: entry.categories?.[0] ?? null,
    setCode: entry.card?.edition?.editioncode ?? null,
    collectorNumber: entry.card?.collectorNumber != null ? String(entry.card.collectorNumber) : null,
    scryfallId: entry.card?.uid ?? null,
  }));

  const commanders = (raw.cards ?? [])
    .filter(entry => entry.categories?.includes('Commander'))
    .map(extractCardName);

  const deck: ArchDeck = {
    id: raw.id,
    name: raw.name ?? '(unnamed)',
    format: raw.deckFormat ?? null,
    commander: commanders.length > 0 ? commanders.join(' / ') : null,
    owner: raw.owner?.username ?? null,
    createdAt: raw.createdAt ?? null,
    updatedAt: raw.updatedAt ?? null,
    cardCount: cards.reduce((sum, card) => sum + card.quantity, 0),
    raw,
  };
  return { deck, cards };
}

/** Group cards by category, "Commander" first, rest alphabetical. */
export function groupCardsByCategory(cards: ArchCard[]): { category: string; cards: ArchCard[] }[] {
  const groups = new Map<string, ArchCard[]>();
  for (const card of cards) {
    const key = card.category ?? '(no category)';
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(card);
  }
  const list = [...groups.entries()].map(([category, groupCards]) => ({
    category,
    cards: groupCards.sort((a, b) => a.cardName.localeCompare(b.cardName)),
  }));
  list.sort((a, b) =>
    a.category === 'Commander' ? -1 : b.category === 'Commander' ? 1 : a.category.localeCompare(b.category)
  );
  return list;
}

/** Plain-text decklist, same format the local app exports. */
export function renderDecklist(deck: ArchDeck, cards: ArchCard[]): string {
  const lines: string[] = [
    `// ${deck.name}`,
    `// Format: ${archFormatName(deck.format)}`,
    ...(deck.commander ? [`// Commander: ${deck.commander}`] : []),
    ...(deck.owner ? [`// Owner: ${deck.owner}`] : []),
    `// https://archidekt.com/decks/${deck.id}`,
    '',
  ];
  for (const group of groupCardsByCategory(cards)) {
    lines.push(`// ${group.category}`);
    for (const card of group.cards) {
      lines.push(`${card.quantity} ${card.cardName}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function safeFilename(name: string, id: number): string {
  const cleaned = name.replace(/[^A-Za-z0-9 _-]/g, '_').trim().slice(0, 60) || 'deck';
  return `${cleaned}_${id}.txt`;
}

export function csvCell(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return '';
  const s = String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Trigger a browser download of generated bytes. */
export function downloadBlob(data: BlobPart, filename: string, mimeType: string): void {
  const url = URL.createObjectURL(new Blob([data], { type: mimeType }));
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}
